[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/pcms/artisan queue:work redis --sleep=1 --tries=3 --timeout=120
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/pcms/storage/logs/worker.log
stopwaitsecs=3600
